website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Proyectos 
      - href: resume.qmd
        text: Resume
      - href: blog.qmd
        text: Blog
    right:
      - icon: linkedin
        href: "https://www.linkedin.com/in/nlebovits/"
      - icon: github
        href: "https://github.com/nlebovits/"