website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: My Work
      - resume.qmd
    right:
      - icon: linkedin
        href: "https://www.linkedin.com/in/nlebovits/"
      - icon: github
        href: "https://github.com/nlebovits/"