--- 
title: "My Work" 
listing:   
  contents: posts   
  sort: "date desc"   
  type: default   
  categories: true   
  sort-ui: false   
  filter-ui: false 
page-layout: full 
title-block-banner: true 
---

### Academic Work
My master's program has allowed me to work on projects that are both educational and practical. A good sample is available on my [RPubs page](https://rpubs.com/nlebovits). In particular, I am proud of the following:

 - [Using NOAA and eBird data to analyze the threat of local sea level rise to avian biodiversity](https://rpubs.com/nlebovits/birds-slr-phl)
 - [Running logistic regressions to predict drunk driving accidents in Philadelphia](https://rpubs.com/nlebovits/musa-500-assign-3)
 - [Calculating LISA statistics and running geographically weighted regressions to explore the relationship between median home value and several neighborhood characteristics in Philadelphia](https://rpubs.com/nlebovits/musa-550-assign-2)

### Gun Crimes Dashboard
Based on the work of [Dr. Eugenia South](https://www.urbanhealthlab.org/eugenia-south), I have been building a dashboard to help community organizations prioritize vacant and abandoned parcels for [anti-gun violence greening interventions](https://www.pnas.org/doi/10.1073/pnas.1718503115). I am currently working to develop a more sustainable, accessible, and reproducible version of the dashboard with a combination of Python and JavaScript. I hope to launch a public version in the fall of 2023. In the meantime, you can see [an ArcGIS draft of the dashboard](https://storymaps.arcgis.com/stories/551f77d85a584705b97c41db7711ba1b) that I made in November of 2022.

### Stewardship & Civic Engagement
I believe strongly in the importance of stewardship and civic engagement. In my free time, I offer pro bono data support to a handful of community organizations and volunteer groups. You can read more about this work [here](/hireme/). Although I have limited capacity to take on more pro bono work at the moment, I offer affordable data consulting services to community organizations. You can learn more on my [Hire Me](/hireme/) page.
